



spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=Renovation_Web_App_DB;integratedSecurity=true;encrypt=true;trustServerCertificate=true;


spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true